apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pdn-shield
  namespace: pdn
spec:
  selector:
    matchLabels:
      app: pdn-shield
  endpoints:
    - port: http
      path: /metrics
      interval: 5s