package detectors

import (
	"regexp"
	"strings"
	"unicode"
	"unicode/utf8"

	"pdn-shield/internal/pii"
)

// citizenshipContext are the keywords that introduce a citizenship value.
var citizenshipContext = []string{
	"гражданство", "гражданин", "гражданка", citizenshipKeyword,
}

// citizenshipFallbackStop are lowercase filler words that must not be treated
// as a country value even when they directly follow a labelled citizenship
// keyword (e.g. "гражданство: не указано").
var citizenshipFallbackStop = map[string]bool{
	"не": true, "нет": true, "неизвестно": true, "отсутствует": true, "н/д": true,
}

// citizenshipFallbackRe matches 1-3 words (any case) after a labelled
// citizenship keyword, up to punctuation. It covers country names not in the
// dictionary and adjective forms (e.g. "гражданство: французское").
var citizenshipFallbackRe = regexp.MustCompile(`^[a-zа-яё-]+(?:\s+[a-zа-яё-]+){0,2}`)

// citizenshipKeyword is the English citizenship keyword.
const citizenshipKeyword = "citizenship"

// countryRF is the "рф" (Russian Federation) abbreviation.
const countryRF = "рф"

// countryForms maps a canonical country name to its inflected forms (lowercase).
// The forms are matched against the lowercased text.
var countryForms = map[string][]string{
	"россия": {"россия", "россии", "россию", "россией", "российская"},
	"рф":     {countryRF},
	"российская федерация":  {"российская федерация", "российской федерации", "российской федерацией"},
	"казахстан":             {"казахстан", "казахстана", "казахстане", "казахстаном"},
	"беларусь":              {"беларусь", "беларуси", "беларусью"},
	"белоруссия":            {"белоруссия", "белоруссии"},
	"узбекистан":            {"узбекистан", "узбекистана", "узбекистане"},
	"таджикистан":           {"таджикистан", "таджикистана", "таджикистане"},
	"киргизия":              {"киргизия", "киргизии"},
	"кыргызстан":            {"кыргызстан", "кыргызстана"},
	"кыргызская республика": {"кыргызская республика", "кыргызской республики", "кыргызской республикой"},
	"армения":               {"армения", "армении", "армению"},
	"азербайджан":           {"азербайджан", "азербайджана", "азербайджане"},
	"азербайджанская республика": {
		"азербайджанская республика", "азербайджанской республики", "азербайджанской республикой",
	},
	"грузия":       {"грузия", "грузии"},
	"молдова":      {"молдова", "молдовы", "молдове"},
	"украина":      {"украина", "украины", "украине"},
	"туркменистан": {"туркменистан", "туркменистана"},
	"вьетнам":      {"вьетнам", "вьетнама", "вьетнаме"},
	"китай":        {"китай", "китая", "китае"},
	"кнр":          {"кнр"},
	"китайская народная республика": {"китайская народная республика", "китайской народной республики"},
	"корея":            {"корея", "кореи"},
	"республика корея": {"республика корея", "республики корея"},
	"турция":           {"турция", "турции"},
	"индия":            {"индия", "индии"},
	"сша":              {"сша"},
	"германия":         {"германия", "германии"},
	"фрг":              {"фрг"},
	"великобритания":   {"великобритания", "великобритании", "великобританию"},
	"израиль":          {"израиль", "израиля"},
	"румыния":          {"румыния", "румынии"},
	"франция":          {"франция", "франции", "францию", "францией"},
	"французская республика": {
		"французская республика", "французской республики", "французской республикой",
	},
	"испания": {"испания", "испании", "испанию", "испанией"},
	"италия":  {"италия", "италии", "италию", "италией"},
	"социалистическая республика вьетнам": {
		"социалистическая республика вьетнам",
		"социалистической республики вьетнам",
	},
	"azerbaijani": {"azerbaijani"},
	"russian":     {"russian"},
	"kazakh":      {"kazakh"},
	"uzbek":       {"uzbek"},
	"tajik":       {"tajik"},
	"armenian":    {"armenian"},
	"georgian":    {"georgian"},
	"moldovan":    {"moldovan"},
	"ukrainian":   {"ukrainian"},
	"turkmen":     {"turkmen"},
	"vietnamese":  {"vietnamese"},
	"chinese":     {"chinese"},
	"korean":      {"korean"},
	"turkish":     {"turkish"},
	"indian":      {"indian"},
	"german":      {"german"},
	"israeli":     {"israeli"},
	"belarusian":  {"belarusian"},
	"kyrgyz":      {"kyrgyz"},
}

// otherUNStates lists the nominative Russian names of UN member states not
// already covered (with their own inflected forms) by countryForms above.
// Their oblique forms are generated by declineCountry, giving broad coverage
// of "гражданин/гражданка <страна>" without hand-writing every inflection.
var otherUNStates = []string{
	// Africa
	"алжир", "ангола", "бенин", "ботсвана", "буркина-фасо", "бурунди", "габон",
	"гамбия", "гана", "гвинея", "гвинея-бисау", "джибути", "египет", "замбия",
	"зимбабве", "кабо-верде", "камерун", "кения", "коморы", "конго",
	"демократическая республика конго", "кот-д’ивуар", "лесото", "либерия",
	"ливия", "маврикий", "мавритания", "мадагаскар", "малави", "мали",
	"марокко", "мозамбик", "намибия", "нигер", "нигерия", "руанда",
	"сан-томе и принсипи", "эсватини", "свазиленд", "сейшелы", "сенегал",
	"сомали", "судан", "южный судан", "сьерра-леоне", "танзания", "того",
	"тунис", "уганда", "центральноафриканская республика", "чад",
	"экваториальная гвинея", "эритрея", "эфиопия", "юар",
	"южно-африканская республика",
	// Asia
	"афганистан", "бангладеш", "бахрейн", "бруней", "бутан",
	"восточный тимор", "индонезия", "иордания", "ирак", "иран", "йемен",
	"камбоджа", "катар", "кипр", "кндр", "кувейт", "лаос", "ливан",
	"малайзия", "мальдивы", "монголия", "мьянма", "непал", "оаэ", "оман",
	"пакистан", "саудовская аравия", "сингапур", "сирия", "таиланд",
	"филиппины", "шри-ланка", "япония",
	// Europe
	"австрия", "албания", "андорра", "бельгия", "болгария",
	"босния и герцеговина", "ватикан", "венгрия", "греция", "дания",
	"ирландия", "исландия", "латвия", "литва", "лихтенштейн", "люксембург",
	"мальта", "монако", "нидерланды", "северная македония", "норвегия",
	"польша", "португалия", "сан-марино", "сербия", "словакия", "словения",
	"финляндия", "хорватия", "черногория", "чехия", "швейцария", "швеция",
	"эстония",
	// Americas
	"антигуа и барбуда", "аргентина", "багамы", "барбадос", "белиз",
	"боливия", "бразилия", "венесуэла", "гаити", "гайана", "гватемала",
	"гондурас", "гренада", "доминика", "доминиканская республика", "канада",
	"колумбия", "коста-рика", "куба", "мексика", "никарагуа", "панама",
	"парагвай", "перу", "сальвадор", "сент-винсент и гренадины",
	"сент-китс и невис", "сент-люсия", "суринам", "тринидад и тобаго",
	"уругвай", "чили", "эквадор", "ямайка",
	// Oceania
	"австралия", "вануату", "кирибати", "маршалловы острова", "микронезия",
	"науру", "новая зеландия", "палау", "папуа-новая гвинея", "самоа",
	"соломоновы острова", "тонга", "тувалу", "фиджи",
}

// declineCountry returns best-effort oblique (non-nominative) case forms for a
// Russian country name, built from a simple ending-based heuristic. It is not
// linguistically exhaustive, but it covers the common genitive/instrumental
// forms used after "гражданин"/"гражданка" (e.g. "Судана", "Кении").
// Multi-word names (e.g. "Кот-д’Ивуар") decline their last word only.
func declineCountry(nom string) []string {
	words := strings.Fields(nom)
	if len(words) == 0 {
		return nil
	}
	last := words[len(words)-1]
	r := []rune(last)
	if len(r) == 0 {
		return nil
	}
	head := ""
	if len(words) > 1 {
		head = strings.Join(words[:len(words)-1], " ") + " "
	}
	stem := string(r[:len(r)-1])
	var endings []string
	switch r[len(r)-1] {
	case 'я':
		endings = []string{"и", "ей", "ю"}
	case 'а':
		endings = []string{"ы", "е", "ой", "у"}
	case 'й':
		endings = []string{"я", "ем", "е"}
	case 'ь':
		endings = []string{"и", "ью"}
	case 'о', 'е', 'и', 'у', 'ы':
		// Indeclinable in common usage (e.g. "Того", "Перу", "Чили").
		return nil
	default:
		// Consonant ending: add the suffix directly (e.g. "Судан" -> "Судана").
		stem = last
		endings = []string{"а", "е", "ом", "у"}
	}
	var forms []string
	for _, e := range endings {
		forms = append(forms, head+stem+e)
	}
	return forms
}

// countryFormList is the flattened list of all country forms, longest first so
// that multi-word forms are matched before their single-word prefixes.
var countryFormList = buildCountryFormList()

func buildCountryFormList() []string {
	var forms []string
	for _, fs := range countryForms {
		forms = append(forms, fs...)
	}
	for _, nom := range otherUNStates {
		if _, exists := countryForms[nom]; exists {
			continue
		}
		forms = append(forms, nom)
		forms = append(forms, declineCountry(nom)...)
	}
	// Sort by length descending so longer phrases match first.
	for i := 1; i < len(forms); i++ {
		for j := i; j > 0 && len(forms[j]) > len(forms[j-1]); j-- {
			forms[j], forms[j-1] = forms[j-1], forms[j]
		}
	}
	return forms
}

// republicRe matches "республика <word>" in any case, e.g. "Республики Армения".
var republicRe = regexp.MustCompile(`республик[аиуойе]?\s+[а-яё]+`)

// citizenshipValueRe matches the value after a citizenship context keyword. It
// captures the country value, skipping separators and filler words. The "sep"
// group captures an explicit label separator (":", "-" or "—"), which marks
// the keyword occurrence as label-anchored for the fallback match.
var citizenshipValueRe = regexp.MustCompile(`^\s*(?P<sep>:|-|—)?\s*(?:заявителя\s*:?\s*|клиента\s*:?\s*)?`)

type citizenshipDetector struct{}

// NewCitizenshipDetector builds the citizenship detector.
func NewCitizenshipDetector() pii.Detector {
	return &citizenshipDetector{}
}

func (d *citizenshipDetector) Name() string { return citizenshipKeyword }

func (d *citizenshipDetector) Categories() []pii.Category {
	return []pii.Category{pii.CatCitizenship}
}

func (d *citizenshipDetector) Detect(text string) []pii.Span {
	return d.DetectLower(pii.Text{Raw: text, Lower: strings.ToLower(text)})
}

func (d *citizenshipDetector) DetectLower(t pii.Text) []pii.Span {
	lower := t.Lower
	if !t.LowerOK() {
		lower = strings.ToLower(t.Raw)
	}
	var spans []pii.Span
	for _, kw := range citizenshipContext {
		spans = append(spans, d.scanKeyword(t, lower, kw)...)
	}
	// Dialog form: a country on its own line that answers a question containing
	// "гражданств".
	spans = append(spans, d.matchDialog(t, lower)...)
	return spans
}

// scanKeyword finds every occurrence of kw in lower and emits a span for each
// value that follows (or precedes, for the English "X citizenship" form).
func (d *citizenshipDetector) scanKeyword(t pii.Text, lower, kw string) []pii.Span {
	var spans []pii.Span
	idx := 0
	for {
		pos := strings.Index(lower[idx:], kw)
		if pos < 0 {
			break
		}
		start := idx + pos
		if !isWholeWord(t.Raw, start, len(kw)) {
			idx = start + len(kw)
			continue
		}
		spans = append(spans, d.matchAtKeyword(t, lower, start, kw)...)
		idx = start + len(kw)
	}
	return spans
}

// matchAtKeyword emits the spans for a single keyword occurrence at start.
func (d *citizenshipDetector) matchAtKeyword(t pii.Text, lower string, start int, kw string) []pii.Span {
	var spans []pii.Span
	if span, ok := d.matchValue(t, lower, start+len(kw)); ok {
		spans = append(spans, span)
	}
	// English "X citizenship": the country precedes the keyword.
	if kw == citizenshipKeyword {
		if span, ok := d.matchBefore(t, lower, start); ok {
			spans = append(spans, span)
		}
	}
	return spans
}

// isWholeWord reports whether the keyword at [start, start+kwLen) is bounded by
// non-letter characters on both sides.
func isWholeWord(raw string, start, kwLen int) bool {
	if start > 0 && isLetterRune(rune(raw[start-1])) {
		return false
	}
	if end := start + kwLen; end < len(raw) && isLetterRune(rune(raw[end])) {
		return false
	}
	return true
}

// matchValue extracts the country value immediately after a context keyword.
func (d *citizenshipDetector) matchValue(t pii.Text, lower string, after int) (pii.Span, bool) {
	rest := lower[after:]
	// Skip separators and filler words.
	skipped := 0
	labeled := false
	if m := citizenshipValueRe.FindStringSubmatchIndex(rest); m != nil {
		skipped = m[1]
		if sepIdx := citizenshipValueRe.SubexpIndex("sep"); sepIdx >= 0 && m[2*sepIdx] >= 0 {
			labeled = true
		}
		rest = rest[m[1]:]
	}
	bestLen := longestCountryPrefix(rest)
	if bestLen > 0 && !labeled && ambiguousCountryWord(t, rest[:bestLen], after+skipped) {
		bestLen = 0
	}
	if bestLen == 0 && labeled {
		bestLen = citizenshipFallbackLen(rest)
	}
	if bestLen == 0 {
		return pii.Span{}, false
	}
	// Compute the byte offset of the value start in the raw text.
	valStart := after + skipped
	valEnd := valStart + bestLen
	return pii.Span{
		Start:      valStart,
		End:        valEnd,
		Category:   pii.CatCitizenship,
		Detector:   d.Name(),
		Confidence: 0.9,
	}, true
}

// citizenshipFallbackLen returns the length of a label-anchored citizenship
// fallback value at the start of rest: 1-3 words (any case) up to punctuation,
// unless the first word is a known filler word (e.g. "не указано"). This
// covers country names outside the dictionary and adjective forms (e.g.
// "гражданство: французское").
func citizenshipFallbackLen(rest string) int {
	m := citizenshipFallbackRe.FindString(rest)
	if m == "" {
		return 0
	}
	first := strings.Fields(m)[0]
	if citizenshipFallbackStop[first] {
		return 0
	}
	return len(m)
}

// longestCountryPrefix returns the length of the longest country form (or
// generic "республика <word>") that prefixes rest.
func longestCountryPrefix(rest string) int {
	bestLen := 0
	for _, form := range countryFormList {
		if strings.HasPrefix(rest, form) && len(form) > bestLen {
			bestLen = len(form)
		}
	}
	// Match "республика <word>" generically.
	if loc := republicRe.FindStringIndex(rest); loc != nil && loc[0] == 0 && loc[1] > bestLen {
		bestLen = loc[1]
	}
	return bestLen
}

// matchBefore extracts a country value that precedes a context keyword, as in
// the English form "holds Azerbaijani citizenship".
func (d *citizenshipDetector) matchBefore(t pii.Text, lower string, kwStart int) (pii.Span, bool) {
	before := lower[:kwStart]
	// Find the longest country form ending at the keyword.
	bestStart := -1
	bestLen := 0
	for _, form := range countryFormList {
		idx := strings.LastIndex(before, form)
		if idx < 0 {
			continue
		}
		// The form must end at the keyword (only whitespace between).
		after := before[idx+len(form):]
		if strings.TrimSpace(after) != "" {
			continue
		}
		if len(form) > bestLen {
			bestLen = len(form)
			bestStart = idx
		}
	}
	if bestStart < 0 {
		return pii.Span{}, false
	}
	return pii.Span{
		Start:      bestStart,
		End:        bestStart + bestLen,
		Category:   pii.CatCitizenship,
		Detector:   d.Name(),
		Confidence: 0.9,
	}, true
}

// matchDialog detects a country on its own line that answers a question
// containing "гражданств".
func (d *citizenshipDetector) matchDialog(t pii.Text, lower string) []pii.Span {
	var spans []pii.Span
	lines := strings.Split(lower, "\n")
	offset := 0
	for i, line := range lines {
		if strings.Contains(line, "гражданств") && strings.Contains(line, "?") {
			// Look at the next line for a country.
			if i+1 < len(lines) {
				spans = append(spans, d.matchDialogNext(lines[i+1], offset+len(line)+1)...)
			}
		}
		offset += len(line) + 1
	}
	return spans
}

// matchDialogNext looks for a country value on the line that follows a
// citizenship question. lineStart is the byte offset of the line in the raw
// text.
func (d *citizenshipDetector) matchDialogNext(next string, lineStart int) []pii.Span {
	// Strip a speaker prefix like "клиент:".
	val := next
	if c := strings.Index(val, ":"); c >= 0 {
		val = val[c+1:]
	}
	val = strings.TrimSpace(val)
	for _, form := range countryFormList {
		if strings.HasPrefix(val, form) {
			// The value sits len(next)-len(val) bytes into the line.
			start := lineStart + (len(next) - len(val))
			return []pii.Span{{
				Start:      start,
				End:        start + len(form),
				Category:   pii.CatCitizenship,
				Detector:   d.Name(),
				Confidence: 0.9,
			}}
		}
	}
	return nil
}

// commonWordCountries are country names that are also ordinary Russian words
// ("того" is a pronoun, "мали" a verb form). Without a label they count as a
// country only when written with a capital letter.
var commonWordCountries = map[string]bool{
	"того": true, "мали": true, "чад": true, "чада": true, "гана": true, "гане": true,
	"гану": true, "куба": true, "кубы": true, "кубе": true, "нигер": true, "оман": true,
	"омана": true, "перу": true, "чили": true, "фиджи": true, "самоа": true, "тонга": true,
}

// ambiguousCountryWord reports whether the matched country form is a common
// word written in lowercase in the raw text.
func ambiguousCountryWord(t pii.Text, form string, rawStart int) bool {
	if !commonWordCountries[form] {
		return false
	}
	if rawStart < 0 || rawStart >= len(t.Raw) {
		return true
	}
	r, _ := utf8.DecodeRuneInString(t.Raw[rawStart:])
	return !unicode.IsUpper(r)
}
